//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGuideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideBook
    {
        public int RSN { get; set; }
        public string GuideBook1 { get; set; }
        public string GuidePostId { get; set; }
        public string Language_Code { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> SignalStrength { get; set; }
        public string Meta { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string C_Id { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string M_Id { get; set; }
        public Nullable<System.DateTime> M_Date { get; set; }
    }
}
